# All information relating to configuring this can be found
# at the wiki on GitHub https://github.com/ShayPunter/Redeemer/wiki/Configuration-Guide
CONFIG-VERSION: 1 #Do not change

redeemables:
  example:
    timesCanRedeem: 5
    permission: "redeem.example"
    commands:
      - "eco give %player% 10"